-- AI Assignment Generation System Database Migration
-- Run this migration to add AI features to your existing database

USE face_attendance_db;

-- =====================================================
-- AI Generation Logs Table
-- Tracks all AI assignment generation attempts
-- =====================================================
CREATE TABLE IF NOT EXISTS ai_generation_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    teacher_id INT NOT NULL,
    template_id INT NULL,
    generation_id VARCHAR(255) UNIQUE NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_format VARCHAR(20) NOT NULL,
    document_size_mb DECIMAL(10,2) NOT NULL,
    questions_requested INT NOT NULL DEFAULT 10,
    questions_generated INT NOT NULL DEFAULT 0,
    generation_time_ms INT NOT NULL DEFAULT 0,
    success_rate DECIMAL(5,2) DEFAULT 0.00,
    
    -- Generation settings as JSON
    generation_settings JSON NOT NULL,
    
    -- Processing stages timing
    parsing_time_ms INT DEFAULT 0,
    preprocessing_time_ms INT DEFAULT 0,
    ai_generation_time_ms INT DEFAULT 0,
    postprocessing_time_ms INT DEFAULT 0,
    
    -- Status tracking
    status ENUM('pending', 'parsing', 'preprocessing', 'generating', 'postprocessing', 'saving', 'completed', 'failed') DEFAULT 'pending',
    error_message TEXT NULL,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    
    -- Foreign keys
    FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (template_id) REFERENCES assignment_templates(id) ON DELETE SET NULL,
    
    -- Indexes for performance
    INDEX idx_teacher_id (teacher_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_generation_id (generation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- Add AI fields to existing assignment_templates table
-- =====================================================
ALTER TABLE assignment_templates 
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE AFTER is_active,
ADD COLUMN IF NOT EXISTS ai_metadata JSON AFTER ai_generated,
ADD COLUMN IF NOT EXISTS generation_id VARCHAR(255) AFTER ai_metadata,
ADD COLUMN IF NOT EXISTS ai_model_version VARCHAR(50) DEFAULT 'phi-3-mini-4k' AFTER generation_id,
ADD COLUMN IF NOT EXISTS source_document_name VARCHAR(255) AFTER ai_model_version,
ADD COLUMN IF NOT EXISTS source_document_hash VARCHAR(64) AFTER source_document_name;

-- Add indexes for AI fields
ALTER TABLE assignment_templates 
ADD INDEX IF NOT EXISTS idx_ai_generated (ai_generated),
ADD INDEX IF NOT EXISTS idx_generation_id (generation_id);

-- =====================================================
-- AI Template Questions Table
-- Stores individual questions generated by AI
-- =====================================================
CREATE TABLE IF NOT EXISTS ai_template_questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    template_id INT NOT NULL,
    generation_id VARCHAR(255) NOT NULL,
    
    -- Question details
    question_order INT NOT NULL DEFAULT 0,
    question_type ENUM('multiple_choice', 'short_answer', 'true_false', 'essay') NOT NULL,
    question_text TEXT NOT NULL,
    
    -- Type-specific content (stored as JSON for flexibility)
    options JSON NULL, -- For multiple choice: ["option1", "option2", "option3", "option4"]
    correct_answer TEXT NULL, -- Correct answer text
    sample_answer TEXT NULL, -- Sample answer for short answer/essay
    explanation TEXT NULL, -- Explanation of the answer
    rubric JSON NULL, -- For essay questions: ["criteria1", "criteria2", ...]
    
    -- Question metadata
    keywords JSON NULL, -- Keywords extracted from source text
    difficulty ENUM('easy', 'medium', 'hard') NOT NULL DEFAULT 'medium',
    estimated_time_minutes INT NOT NULL DEFAULT 2,
    complexity_score INT NOT NULL DEFAULT 1,
    max_score DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    
    -- AI generation metadata
    source_chunk TEXT NULL, -- Original text chunk used to generate question
    ai_confidence DECIMAL(3,2) DEFAULT 0.80, -- AI confidence in question quality (0.0-1.0)
    processing_notes TEXT NULL, -- Any processing notes or warnings
    
    -- Quality metrics
    validation_passed BOOLEAN DEFAULT TRUE,
    quality_score DECIMAL(3,2) DEFAULT 0.75,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Foreign keys
    FOREIGN KEY (template_id) REFERENCES assignment_templates(id) ON DELETE CASCADE,
    FOREIGN KEY (generation_id) REFERENCES ai_generation_logs(generation_id) ON DELETE CASCADE,
    
    -- Indexes
    INDEX idx_template_id (template_id),
    INDEX idx_generation_id (generation_id),
    INDEX idx_question_order (question_order),
    INDEX idx_question_type (question_type),
    INDEX idx_difficulty (difficulty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- AI System Statistics Table
-- Tracks overall system performance and usage
-- =====================================================
CREATE TABLE IF NOT EXISTS ai_system_stats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date_recorded DATE NOT NULL,
    
    -- Generation statistics
    total_generations INT DEFAULT 0,
    successful_generations INT DEFAULT 0,
    failed_generations INT DEFAULT 0,
    total_questions_generated INT DEFAULT 0,
    
    -- Performance metrics
    avg_generation_time_ms INT DEFAULT 0,
    avg_questions_per_generation DECIMAL(5,2) DEFAULT 0,
    avg_success_rate DECIMAL(5,2) DEFAULT 0,
    
    -- Document processing stats
    documents_processed INT DEFAULT 0,
    total_documents_size_mb DECIMAL(10,2) DEFAULT 0,
    most_common_format VARCHAR(20),
    
    -- Question type distribution
    multiple_choice_count INT DEFAULT 0,
    short_answer_count INT DEFAULT 0,
    true_false_count INT DEFAULT 0,
    essay_count INT DEFAULT 0,
    
    -- Difficulty distribution
    easy_questions INT DEFAULT 0,
    medium_questions INT DEFAULT 0,
    hard_questions INT DEFAULT 0,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    UNIQUE KEY unique_date (date_recorded),
    INDEX idx_date_recorded (date_recorded)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- AI Model Performance Table
-- Tracks different AI model versions and their performance
-- =====================================================
CREATE TABLE IF NOT EXISTS ai_model_performance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    model_name VARCHAR(100) NOT NULL,
    model_version VARCHAR(50) NOT NULL,
    
    -- Performance metrics
    total_uses INT DEFAULT 0,
    avg_generation_time_ms INT DEFAULT 0,
    avg_quality_score DECIMAL(3,2) DEFAULT 0,
    success_rate DECIMAL(5,2) DEFAULT 0,
    
    -- Configuration used
    model_config JSON,
    
    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    last_used_at TIMESTAMP NULL,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    UNIQUE KEY unique_model_version (model_name, model_version),
    INDEX idx_model_name (model_name),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- Insert default AI model record
-- =====================================================
INSERT IGNORE INTO ai_model_performance (model_name, model_version, model_config, is_active) 
VALUES (
    'phi-3-mini-4k-instruct', 
    '1.0', 
    JSON_OBJECT(
        'maxTokens', 2048,
        'temperature', 0.7,
        'topP', 0.9,
        'language', 'vietnamese'
    ),
    TRUE
);

-- =====================================================
-- Views for easier querying
-- =====================================================

-- AI Generation Summary View
CREATE OR REPLACE VIEW ai_generation_summary AS
SELECT 
    l.id,
    l.generation_id,
    l.teacher_id,
    u.full_name as teacher_name,
    l.document_name,
    l.document_format,
    l.questions_requested,
    l.questions_generated,
    l.generation_time_ms,
    l.success_rate,
    l.status,
    l.created_at,
    t.title as template_title,
    t.id as template_id
FROM ai_generation_logs l
LEFT JOIN users u ON l.teacher_id = u.id
LEFT JOIN assignment_templates t ON l.template_id = t.id
ORDER BY l.created_at DESC;

-- AI Questions Summary View  
CREATE OR REPLACE VIEW ai_questions_summary AS
SELECT 
    q.id,
    q.template_id,
    q.generation_id,
    q.question_type,
    q.difficulty,
    q.estimated_time_minutes,
    q.complexity_score,
    q.ai_confidence,
    q.quality_score,
    q.validation_passed,
    t.title as template_title,
    l.teacher_id,
    u.full_name as teacher_name
FROM ai_template_questions q
LEFT JOIN assignment_templates t ON q.template_id = t.id
LEFT JOIN ai_generation_logs l ON q.generation_id = l.generation_id
LEFT JOIN users u ON l.teacher_id = u.id
ORDER BY q.created_at DESC;

-- =====================================================
-- Stored Procedures for AI Statistics
-- =====================================================

DELIMITER //

-- Update daily AI statistics
CREATE PROCEDURE IF NOT EXISTS UpdateAIStats(IN target_date DATE)
BEGIN
    INSERT INTO ai_system_stats (
        date_recorded,
        total_generations,
        successful_generations,
        failed_generations,
        total_questions_generated,
        avg_generation_time_ms,
        avg_questions_per_generation,
        documents_processed,
        total_documents_size_mb,
        multiple_choice_count,
        short_answer_count,
        true_false_count,
        essay_count,
        easy_questions,
        medium_questions,
        hard_questions
    )
    SELECT 
        target_date,
        COUNT(*) as total_generations,
        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) as successful_generations,
        SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) as failed_generations,
        SUM(questions_generated) as total_questions_generated,
        AVG(generation_time_ms) as avg_generation_time_ms,
        AVG(questions_generated) as avg_questions_per_generation,
        COUNT(*) as documents_processed,
        SUM(document_size_mb) as total_documents_size_mb,
        (SELECT COUNT(*) FROM ai_template_questions WHERE DATE(created_at) = target_date AND question_type = 'multiple_choice'),
        (SELECT COUNT(*) FROM ai_template_questions WHERE DATE(created_at) = target_date AND question_type = 'short_answer'),
        (SELECT COUNT(*) FROM ai_template_questions WHERE DATE(created_at) = target_date AND question_type = 'true_false'),
        (SELECT COUNT(*) FROM ai_template_questions WHERE DATE(created_at) = target_date AND question_type = 'essay'),
        (SELECT COUNT(*) FROM ai_template_questions WHERE DATE(created_at) = target_date AND difficulty = 'easy'),
        (SELECT COUNT(*) FROM ai_template_questions WHERE DATE(created_at) = target_date AND difficulty = 'medium'),
        (SELECT COUNT(*) FROM ai_template_questions WHERE DATE(created_at) = target_date AND difficulty = 'hard')
    FROM ai_generation_logs 
    WHERE DATE(created_at) = target_date
    ON DUPLICATE KEY UPDATE
        total_generations = VALUES(total_generations),
        successful_generations = VALUES(successful_generations),
        failed_generations = VALUES(failed_generations),
        total_questions_generated = VALUES(total_questions_generated),
        avg_generation_time_ms = VALUES(avg_generation_time_ms),
        avg_questions_per_generation = VALUES(avg_questions_per_generation),
        documents_processed = VALUES(documents_processed),
        total_documents_size_mb = VALUES(total_documents_size_mb),
        multiple_choice_count = VALUES(multiple_choice_count),
        short_answer_count = VALUES(short_answer_count),
        true_false_count = VALUES(true_false_count),
        essay_count = VALUES(essay_count),
        easy_questions = VALUES(easy_questions),
        medium_questions = VALUES(medium_questions),
        hard_questions = VALUES(hard_questions);
END //

DELIMITER ;

-- =====================================================
-- Sample Data for Testing (Optional)
-- =====================================================

-- Insert sample AI generation log (commented out for production)
/*
INSERT INTO ai_generation_logs (
    teacher_id, generation_id, document_name, document_format, document_size_mb,
    questions_requested, questions_generated, generation_time_ms, success_rate,
    generation_settings, status
) VALUES (
    1, 'test_gen_001', 'sample_document.pdf', 'pdf', 1.5,
    10, 8, 15000, 80.00,
    JSON_OBJECT(
        'question_types', JSON_ARRAY('multiple_choice', 'short_answer'),
        'difficulty', 'medium',
        'language', 'vietnamese'
    ),
    'completed'
);
*/

-- =====================================================
-- Verification Queries
-- =====================================================

-- Check if all tables were created successfully
SELECT 
    TABLE_NAME,
    TABLE_ROWS,
    CREATE_TIME
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = DATABASE() 
AND TABLE_NAME LIKE '%ai_%'
ORDER BY TABLE_NAME;

-- Check if assignment_templates columns were added
SHOW COLUMNS FROM assignment_templates LIKE '%ai_%';

COMMIT;

-- =====================================================
-- Migration Complete
-- =====================================================
SELECT 'AI Assignment Generation System database migration completed successfully!' as result;